### ISSUE TITLE
buffer not terminated, parse_config.c, #2

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#10]
83        if (!configp->shape_func[0])
   	
CID 208895 (#1 of 1): Buffer not null terminated (BUFFER_SIZE)
2. buffer_size: Calling strncpy with a source string whose length (15 chars) is greater than or equal to the size argument (15) will fail to null-terminate configp->shape_func.

 84                strncpy(configp->shape_func, "single-step,0.1", 15);

**Comment by NoorMubeen** [comment]
fixed
