### ISSUE TITLE
gcc 9.2.1 is throwing a warning when compiling src/logger.c

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#15]
gcc 9.2.1 is throwing a warning when compiling src/logger.c:

gcc -D VERSION=\"0.1\" -D_LINUX_ -Wall -O2   -c -o src/logger.o src/logger.c
In file included from /usr/include/string.h:494,
                 from src/logger.c:22:
In function ‘strncpy’,
    inlined from ‘find_path’ at src/logger.c:210:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/logger.c: In function ‘find_path’:
src/logger.c:210:2: note: length computed here
  210 |  strncpy(buf+sz, replace, strlen(replace));

**Comment by NoorMubeen** [comment]
this was fixed in commit c36421c
