### ISSUE TITLE
negative sz causing a buffer under-run on final_buf[] in src/logger.c

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#16]
Static analysis has found a potential buffer under-run on final_buf[].  I believe this is a theoretically possible issue only if col_desc[i].report_enabled is false for all col_desc[] objects.  It maybe worth just adding a santity check on sz to make sure the code is 100% safe from buffer underruns

assignment: Assigning: sz = sz - 7UL + 2UL. The value of sz is now -5.
744        sz = sz - sizeof(delim) + 2;
   CID 92458 (#2 of 2): Out-of-bounds write (OVERRUN)

underrun-local: Underrunning array final_buf at byte offset -6 using index sz - 1 (which evaluates to -6).
745        final_buf[sz-1] = '\n';
Out-of-bounds write (OVERRUN)
746        final_buf[sz] = '\0';

**Comment by ColinIanKing** [comment]
Any updates for a fix on this?

**Comment by NoorMubeen** [comment]
this was fixed in  commit c36421c

**Comment by ColinIanKing** [comment]
Ah, thanks. I missed that.
