### ISSUE TITLE
build falures with gcc-10

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#17]
Hi,

building with gcc-10 has some build failures.

gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/parse_config.o src/parse_config.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/logger.o src/logger.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/rapl.o src/rapl.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/perf_msr.o src/perf_msr.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/psst.o src/psst.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2 -DPASS2 ./src/parse_config.o ./src/logger.o ./src/rapl.o ./src/perf_msr.o ./src/psst.o  -o psst -lpthread -lrt -lm
/usr/bin/ld: ./src/psst.o:(.bss+0x34): multiple definition of `exit_cpu_thread'; ./src/logger.o:(.bss+0x1f4): first defined here
/usr/bin/ld: ./src/psst.o:(.bss+0x0): multiple definition of `dev_msr_supported'; ./src/perf_msr.o:(.data+0x0): first defined here
/usr/bin/ld: ./src/psst.o:(.bss+0x20): multiple definition of `soc_diff_uj'; ./src/logger.o:(.bss+0x20): first defined here
/usr/bin/ld: ./src/psst.o:(.bss+0x28): multiple definition of `pp0_diff_uj'; ./src/logger.o:(.bss+0x40): first defined here
/usr/bin/ld: ./src/psst.o:(.bss+0x30): multiple definition of `exit_io_thread'; ./src/logger.o:(.bss+0x1f0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:22: psst] Error 1

**Comment by ColinIanKing** [comment]
Some of these symbols may need to be externs but some maybe duplicated but need to be static - I can't figure these out from the intent of the code.  Can this be fixed as this is causing problems with building this with Debian, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957715

**Comment by NoorMubeen** [comment]
will fix this soon.

**Comment by NoorMubeen** [comment]
To clean up the inadvertent globals, I have pushed commit 9099338
However, i was not able to reproduce with gcc-10; can you reconfirm if fixed on the tip ?

**Comment by ColinIanKing** [comment]
That's perfect!

make 
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/parse_config.o src/parse_config.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/logger.o src/logger.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/rapl.o src/rapl.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/perf_msr.o src/perf_msr.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2   -c -o src/psst.o src/psst.c
gcc-10 -D VERSION=\"1.0\" -D_LINUX_ -Wall -O2 -DPASS2 ./src/parse_config.o ./src/logger.o ./src/rapl.o ./src/perf_msr.o ./src/psst.o  -o psst -lpthread -lrt -lm

thank you for such a speedy fix.

Colin

**Comment by ColinIanKing** [comment]
BTW, to make it build with gcc-10 I had to do:
diff --git a/Makefile b/Makefile
index 4dda545..3d67431 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ VERSION = 1.0
 BINDIR = /usr/bin
 MANDIR = /usr/share/man/man1
 WARNFLAGS = -Wall -Wformat
-CC = gcc
+CC = gcc-10
 CFLAGS += -D VERSION=\"$(VERSION)\"
 CFLAGS += -D_LINUX_ -Wall -O2
 DBG_CFLAGS = -DDEBUG -g -O0

**Comment by NoorMubeen** [comment]
> +CC = gcc-10

I tried exactly the same after : sudo add-apt-repository ppa:ubuntu-toolchain-r/test
it wouldn't trip. anyway thanks for confirming & closing.
