### ISSUE TITLE
tick_usec is not set in src/psst.c:268

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#2]
Building with clang's scan-build a bug is detected where tick_usec is not initialized and contains garbage value. This occurs if the previous if statement "if (CPU_ISSET(pr, &configpv.cpumask))" is false and tick_usec is not set.

/usr/share/clang/scan-build-5.0/bin/../libexec/ccc-analyzer -D VERSION=\"0.1\" -D_LINUX_ -Wall -O2   -c -o src/psst.o src/psst.c
src/psst.c:268:26: warning: The left operand of '*' is a garbage value
        on_time_us = (tick_usec * duty_cycle / 100);

**Comment by NoorMubeen** [comment]
fixed as of commit 5fc84756584a1bb962923b3676ae1659bf5a8764
