### ISSUE TITLE
write failures in the logger are silently ignored

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#3]
In the case where writes fail, the logger just ignores these write failures:

src/logger.c:299:4: warning: Value stored to 'wr_sz' is never read
                        wr_sz = write(cfg->log_file_fd, dirty_pg,
                        ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/logger.c:304:4: warning: Value stored to 'wr_sz' is never read
                        wr_sz = write(cfg->log_file_fd, active_pg,
                        ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/logger.c:692:3: warning: Value stored to 'sz' is never read
                sz = write(configpv.log_file_fd, log_header, sz);

Perhaps these return values need some error checking?

**Comment by NoorMubeen** [comment]
fixed as of 5fc84756584a1bb962923b3676ae1659bf5a8764
