### ISSUE TITLE
logger is computing col_desc[i].value using potentially uninitialized values 

### ISSUE THREAD

**Issue by ColinIanKing** [intel/psst#4]
In the following case in logger.c, aperf_diff and mperf_diff may contain garbage values when dev_msr_supported is false.  I think that could be a bug.

                case FREQ_REALIZED:
                        /* real freq = TSC* delta-aperf/delta-mperf */
                        col_desc[i].value = (float)cpu_khz *
                                                aperf_diff/mperf_diff;

**Comment by NoorMubeen** [comment]
this is functionally not a possibility. nevertheless fixed in :5fc84756584a1bb962923b3676ae1659bf5a8764
